---
title: "The power of the tidyverse: manipulating data"
description: |
  In this post I will show you how to use the basic tools from tidyverse. This tools are useful to deal with a whole sort of data.
author:
  - name: Guilherme Bastos Gomes
    url: https://gbastosg.github.io/guilhermesportfolio/
date: 2022-04-13
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello! In this post I will show you how to use the basic verbs of the tidyverse:

* select()
* arrange()
* filter()
* mutate()

All these verbs are also great *functions* to deal with data from the real world, but since gathering this data can be very time useful we will use a built in dataset from R.

Let's have a look in the Iris dataset which gives the measurements in centimeters of the variables sepal length, sepal width, petal length and petal width, respectively, for 50 flowers from each of 3 species of iris. The species are *Iris setosa*, *Iris versicolor*, and *Iris virginica*.

And of course since we are dealing with the tidyverse we have to call it:

`library(tidyverse)`

we can call it and have a look:
`iris`
or just a part of it:
`head(iris)`
or just a glimpse for those who love stats:
`glimpse(iris)`

First of all let's start with select and since we are using a tidyverse way of thinking, we are going to start using *pipes* also known as *%>%* or *|>*, depends on which you prefer to write.

So, to select a sort of columns you wish you can:

```
iris %>% #here we are calling the data
select(Sepal.Length, Species) #here we are calling the function and  choosing two columns `Sepal.Length` and `Species`
```

Note the pipe "%>%", that means that the output of one function will be the input of the next one, and the first pipe just includes the iris data set into the next function `select(Sepal.Length, Species)`

Pretty easy, right?

Now you should have a smaller data set, only the selected columns from iris to work with, if you want to check it, just call the same script again, but using the `head()` function to see only the first 10 lines:

```
iris %>%
select(Sepal.Length, Species) %>%
head()
```

Now you should have something like this:

| Sepal.Length | Species |
|--------------|---------|
| 5.1          | setosa  | 
| 4.9          | setosa  | 
| 4.7          | setosa  | 
| 4.6          | setosa  | 
| 5.0          | setosa  |
| 5.4          | setosa  |


To make our work even easier, we should create an object with our smaller iris `dataframe`:

```
selected_iris <- iris %>%
select(Sepal.Length, Species) %>%
head()
```
Suppose you want now to quick check the distribution of Sepal Lengths, we can either call the `view()` function inside RStudio, or use the `arrange()` function, like this:

```
arrange(selected_iris) %>%
head()
```

You should see something like this:

| Sepal.Length  | Species |
|---------------|---------|
| 4.3           | setosa  |
| 4.4           | setosa  |
| 4.4           | setosa  |
| 4.4           | setosa  |
| 4.5           | setosa  |
| 4.6           | setosa  |

You will notice that the `dataframe` is now ordered from the lowest to the highest values of Sepal.Length. But what if we wanted to arrange in a descending order? Then we should just use the function desc() inside of our arrange() calling:

```
arrange(desc(selected_iris)) %>%
head()
```

Now you will have:

| Sepal.Length | Species    |
|--------------|------------|
| 7.9          |  virginica |
| 7.7          |  virginica |
| 7.7          |  virginica |
| 7.7          |  virginica |
| 7.7          |  virginica |
| 7.6          |  virginica |






